In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [99]:
ds = pd.read_csv("Churn_Modelling.csv")
ds

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
ds.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [100]:
df = ds[ds.columns[3:14]]
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [101]:
df["Gender"] = pd.get_dummies(df["Gender"],drop_first=True)
df

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [102]:
df[["Germany","Spain"]]=pd.get_dummies(df["Geography"],drop_first=True)
df

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  Germany  Spain  
0             1               1        101348.88       1        0      0  
1             0               1        112542.58       0        0      1  
2             1               0        113931.57       1        0      0  
3             0               0         93826.63       0        0      0  
4             1               1         79084.10       0        0      1  
...         ...             ...              ...     ...      ...    ...  
9995          1               0         96270.64       0        0      0  
9996          1               1        101699.77       0        0      0  
9997          0               1         42085.58       1        0      0  
9998          1               0         92888.52       1        1      0  
9999          1               0         38190.78       0        0      0  

[10000 rows x 13 columns]

In [103]:
df.drop("Geography",axis=1,inplace=True)
df

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4102: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Germany  Spain  
0                  1        101348.88       1        0      0  
1                  1        112542.58       0        0      1  
2                  0        113931.57       1        0      0  
3                  0         93826.63       0        0      0  
4                  1         79084.10       0        0      1  
...              ...              ...     ...      ...    ...  
9995               0         96270.64       0        0      0  
9996               1        101699.77       0        0      0  
9997               1         42085.58       1        0      0  
9998               0         92888.52       1        1      0  
9999               0         38190.78       0        0      0  

[10000 rows x 12 columns]

In [45]:
df.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Germany',
       'Spain'],
      dtype='object')

In [104]:
X =df[['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Germany',
       'Spain']].values

In [105]:
X

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0134888e+05,
        0.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 0.0000000e+00, 4.1000000e+01, ..., 1.1254258e+05,
        0.0000000e+00, 1.0000000e+00],
       [5.0200000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.1393157e+05,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 4.2085580e+04,
        0.0000000e+00, 0.0000000e+00],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 9.2888520e+04,
        1.0000000e+00, 0.0000000e+00],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 3.8190780e+04,
        0.0000000e+00, 0.0000000e+00]])

In [106]:
Y = df["Exited"].values
Y

array([1, 0, 1, ..., 1, 1, 0])

# Random Forest

In [107]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score

In [108]:
from sklearn.preprocessing import StandardScaler
stscaler = StandardScaler()
X = stscaler.fit_transform(X)

In [109]:
X

array([[-0.32622142, -1.09598752,  0.29351742, ...,  0.02188649,
        -0.57873591, -0.57380915],
       [-0.44003595, -1.09598752,  0.19816383, ...,  0.21653375,
        -0.57873591,  1.74273971],
       [-1.53679418, -1.09598752,  0.29351742, ...,  0.2406869 ,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -1.09598752, -0.27860412, ..., -1.00864308,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.91241915,  0.29351742, ..., -0.12523071,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.09598752, -1.04143285, ..., -1.07636976,
        -0.57873591, -0.57380915]])

In [118]:
# Divide dataset  into training and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size =0.2 , random_state=0)

In [119]:
regressor = RandomForestClassifier(n_estimators=200,criterion="entropy",random_state=0)
regressor.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [122]:
regressor.score(X_test,Y_test)

0.8705

In [57]:
regressor.predict(X)

array([0.75666667, 0.16      , 0.98      , ..., 0.68666667, 0.67666667,
       0.02      ])

In [95]:
Y_test

array([0, 1, 0, ..., 0, 0, 0])

In [96]:
regressor.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

# DB SCAN

In [59]:
from sklearn.cluster import DBSCAN

In [60]:
data =X

In [61]:
from sklearn.preprocessing import StandardScaler
stscaler = StandardScaler()
data = stscaler.fit_transform(data)

In [73]:
dbsc = DBSCAN(eps = 0.6, min_samples=20).fit(data)
dbsc.labels_

array([-1, -1, -1, ..., -1, -1, -1])

In [63]:
labels = dbsc.labels_
core_samples = np.zeros_like(labels,dtype=bool)
core_samples[dbsc.core_sample_indices_]=True

In [64]:
labels

array([-1, -1, -1, ..., -1, -1, -1])

In [ ]:
data

# Hierarchial

In [ ]:
from sklearn import preprocessing
data = preprocessing.normalize(X)
# using dendrogram to find the optimal number of clusters
import scipy.cluster.hierarchy as sch
dendrogram=sch.dendrogram(sch.linkage(data,method='ward'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean distance')
plt.show()

In [76]:
from sklearn.cluster import AgglomerativeClustering
hc=AgglomerativeClustering(n_clusters= 2, affinity= 'euclidean', linkage= 'ward')
y_hc=hc.fit_predict(X)
y_hc

array([1, 0, 0, ..., 1, 0, 0])

In [79]:
Y

array([1, 0, 1, ..., 1, 1, 0])

# Artificial Neural Network (ANN)

In [124]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [125]:
classifier = Sequential()

In [128]:
classifier.add(Dense(output_dim=6,init = "uniform", activation="relu",input_dim=11))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [130]:
classifier.add(Dense(output_dim=6,init="uniform",activation="relu"))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=2, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [131]:
classifier.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [132]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [138]:
classifier.fit(X_train,Y_train,batch_size=1000,nb_epoch=50)

Epoch 1/50
8000/8000 [==============================] - 0s 3us/step - loss: 0.3320 - accuracy: 0.8644
Epoch 2/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8643
Epoch 3/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8646
Epoch 4/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8643
Epoch 5/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8644
Epoch 6/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8640
Epoch 7/50
1000/8000 [==>...........................] - ETA: 0s - loss: 0.3285 - accuracy: 0.8570

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8644
Epoch 8/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3319 - accuracy: 0.8643
Epoch 9/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8644
Epoch 10/50
8000/8000 [==============================] - 0s 3us/step - loss: 0.3320 - accuracy: 0.8641
Epoch 11/50
8000/8000 [==============================] - 0s 3us/step - loss: 0.3319 - accuracy: 0.8645
Epoch 12/50
8000/8000 [==============================] - 0s 5us/step - loss: 0.3320 - accuracy: 0.8643
Epoch 13/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8639
Epoch 14/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3319 - accuracy: 0.8641
Epoch 15/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3320 - accuracy: 0.8644
Epoch 16/50
8000/8000 [==============================] - 0s 4us/step - loss: 0.3319 - a

In [140]:
Y_pred = classifier.predict(X_test)

In [148]:
Y_pred = Y_pred > 0.5

In [165]:
Y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [146]:
Y_test

array([0, 1, 0, ..., 0, 0, 0])

In [150]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,Y_pred)

array([[1512,   83],
       [ 195,  210]])

In [151]:
1722/2000

0.861

In [152]:
df.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Germany',
       'Spain'],
      dtype='object')

In [161]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Germany  Spain  
0               1        101348.88       1        0      0  
1               1        112542.58       0        0      1  
2               0        113931.57       1        0      0  
3               0         93826.63       0        0      0  
4               1         79084.10       0        0      1

In [168]:
classifier.predict(stscaler.transform(np.array([[600,1,40,3,60000,2,1,1,50000,0,0]])))

array([[0.0289514]], dtype=float32)

In [188]:
Y_pred = classifier.predict(X)

In [176]:
Y_pred

array([[0.43101594],
       [0.28156108],
       [0.97585183],
       ...,
       [0.161208  ],
       [0.14046247],
       [0.16233252]], dtype=float32)

In [178]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    -0.326221 -1.095988  0.293517 -1.041760 -1.225848 -0.911583  0.646092   
1    -0.440036 -1.095988  0.198164 -1.387538  0.117350 -0.911583 -1.547768   
2    -1.536794 -1.095988  0.293517  1.032908  1.333053  2.527057  0.646092   
3     0.501521 -1.095988  0.007457 -1.387538 -1.225848  0.807737 -1.547768   
4     2.063884 -1.095988  0.388871 -1.041760  0.785728 -0.911583  0.646092   
...        ...       ...       ...       ...       ...       ...       ...   
9995  1.246488  0.912419  0.007457 -0.004426 -1.225848  0.807737  0.646092   
9996 -1.391939  0.912419 -0.373958  1.724464 -0.306379 -0.911583  0.646092   
9997  0.604988 -1.095988 -0.278604  0.687130 -1.225848 -0.911583 -1.547768   
9998  1.256835  0.912419  0.293517 -0.695982 -0.022608  0.807737  0.646092   
9999  1.463771 -1.095988 -1.041433 -0.350204  0.859965 -0.911583  0.646092   

             7         8         9        10  
0     0.970243  0.021886 -0.578736 -0.573809  
1     0.970243  0.216534 -0.578736  1.742740  
2    -1.030670  0.240687 -0.578736 -0.573809  
3    -1.030670 -0.108918 -0.578736 -0.573809  
4     0.970243 -0.365276 -0.578736  1.742740  
...        ...       ...       ...       ...  
9995 -1.030670 -0.066419 -0.578736 -0.573809  
9996  0.970243  0.027988 -0.578736 -0.573809  
9997  0.970243 -1.008643 -0.578736 -0.573809  
9998 -1.030670 -0.125231  1.727904 -0.573809  
9999 -1.030670 -1.076370 -0.578736 -0.573809  

[10000 rows x 11 columns]

In [189]:
ds["Rating"] = Y_pred

In [192]:
ds.sort_values("Rating",ascending=True).head(10)

RowNumber  CustomerId      Surname  CreditScore Geography Gender  Age  \
4716       4717    15805764     Hallahan          646    France   Male   18   
1953       1954    15675190         Chia          623    France   Male   21   
5872       5873    15684248         Meng          658     Spain   Male   21   
6309       6310    15785342        Shipp          705    France   Male   25   
5707       5708    15649451        Yates          746    France   Male   25   
6966       6967    15689661     Gorbunov          663    France   Male   22   
9563       9564    15624374      Maclean          703    France   Male   28   
7666       7667    15813192  Chukwuemeka          494    France   Male   25   
9729       9730    15615330   Tretiakova          651    France   Male   23   
6103       6104    15571144         Ives          655    France   Male   28   

      Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
4716      10      0.0              2          0               1   
1953      10      0.0              2          0               1   
5872       7      0.0              2          0               1   
6309       9      0.0              2          0               1   
5707       9      0.0              2          0               1   
6966       6      0.0              2          0               1   
9563       9      0.0              2          0               1   
7666       6      0.0              2          0               1   
9729      10      0.0              2          1               1   
6103      10      0.0              2          0               1   

      EstimatedSalary  Exited    Rating  
4716         52795.15       0  0.002300  
1953        135851.30       0  0.002705  
5872        154279.87       0  0.003004  
6309        112331.19       0  0.003044  
5707         88728.47       0  0.003101  
6966        131827.15       0  0.003283  
9563          2151.17       0  0.003478  
7666        109988.09       0  0.003551  
9729        170099.23       0  0.003573  
6103        126565.21       0  0.003587